### ISSUE TITLE
How to change folder icons ?

### ISSUE THREAD

**Issue by DraGiuS** [EliverLara/Aqua#1]
Hi, on your screenshots, the folder icons are differents than the default zafiro folders.
How to change them ?

**Comment by EliverLara** [comment]
HI, you're right, I've changed the folders design, I can send them by email if you want.

**Comment by DraGiuS** [comment]
Hi, if you send me these icons, i take them, thanks

**Comment by DraGiuS** [comment]
You can send me them via google drive or mega

**Comment by EliverLara** [comment]
[Aqua icons](https://drive.google.com/file/d/0ByEI8YulWVD3dHl1UzZ0eDdtbFV4TGl3MGRDa2VyTjEtWVFj/view?usp=drivesdk)

**Comment by DraGiuS** [comment]
Thanks

**Comment by vaahxx** [comment]
thank you, I'm in love with these theme!
