### ISSUE TITLE
Aqua-Dark not work in Thunar

### ISSUE THREAD

**Issue by Sup3r-Us3r** [EliverLara/Aqua#5]
### When selecting some folder does not show the name of this folder, I will provide some screenshots to better illustrate what I mean:

------

* **Thunar:** https://i.lensdump.com/i/8hvsao.png
* **Nautilus:** https://i.lensdump.com/i/8hvywH.png

------

Would you provide some correction for this? because I really liked the theme.
Sorry for my English, I'm from Brazil, and I do not speak very well.

**Comment by EliverLara** [comment]
HI, your screenshots are not available, could you attach the here please?

**Comment by Sup3r-Us3r** [comment]
# Sorry, I fix the link, thank you!

## **Thunar:** ![Thunar](https://i.lensdump.com/i/8hvsao.png)
------
## **Nautilus:** ![Nautilus](https://i.lensdump.com/i/8hvywH.png)

`As you can see, on Thunar, when selecting the folder, its name disappears, it does not happen in Nautilus, I loved its theme, I want to use it very much, if possible correct this error, thank you in advance!`

**Comment by EliverLara** [comment]
Thanks! I see now, i'd like to know details about your OS like gtk version, thunar version, etc.

**Comment by Sup3r-Us3r** [comment]
OS: Arch Linux | Rolling Release | 64bits
Thunar: Thunar 1.8.1git-f5147445 (Xfce 4.12)

My Arch Linux is rolling release, all packages are in their latest version.

**Muchas gracias por haber respondido :D**

**Comment by EliverLara** [comment]
¿Podrias verificar si esta resuelto con el ultimo commit?

**Comment by EliverLara** [comment]
Excelente!, me alegra que le guste mi trabajo, un saludo.
